@RabbitMqTraining.Api_HostAddress = http://localhost:5242

### Create Order
POST {{RabbitMqTraining.Api_HostAddress}}/api/orders
Content-Type: application/json

{
  "orderId": 1001,
  "customer": "Patrick",
  "amount": 49.99
}